# @brief   hcasl Makefile for Unix like environment.
# @author  eel3
# @date    2015/10/11
#
# @note
# - GCC 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) on Ubuntu 12.04.5 LTS x86

app        := hcasl
CFLAGS     += -Wall -ansi -pedantic

.PHONY: all
all: $(app)

.PHONY: clean
clean:
	$(RM) $(app)
