# @brief   hcasl Makefile for Unix like environment.
# @author  eel3
# @date    2015/10/07
#
# @note
# - Apple LLVM 6.0 (clang-600.0.57, Xcode 6.2) on Mac OS X 10.9.5

app        := hcasl
CXXFLAGS   += -Wall -std=c++11 -pedantic

.PHONY: all
all: $(app)

.PHONY: clean
clean:
	$(RM) $(app)
