#!/usr/bin/env bash
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
# @(#) Command line tool for "head -c N && shift 1 byte/char" loop. Version 1.0.1.20151109

set -u
umask 0022
IFS=`printf ' \t\n_'`; IFS=${IFS%_}
PATH=/bin:/usr/bin
export IFS PATH

readonly progname=`basename "$0"`

echo $progname | grep -q '^hcasl-char' || export LC_ALL=C LANG=C

# usage <status>
usage() {
    cat <<- EOT
		usage: $progname [options] [file...]
		    -n N
		      print the N bytes per line (N >= 1)
		    -o FILE
		      place output in file FILE
	EOT
    exit $1
}

# version (nop)
version() {
    echo "$progname 1.0.0"
    exit 0
}

# error <message>
error() {
    echo "$progname:" "$@" 1>&2
    exit 1
}

# tobytes <bytes>
tobytes() {
    [ "$1" -eq 0 ] 2>/dev/null
    [ $? -lt 2 ] || return 1
    [ "$1" -ge 1 ] || return 1
    echo "$1"
}

bytes=8
output=

opt=
while getopts 'hn:o:v' opt; do
    case $opt in
    h)      usage 0 ;;
    n)      bytes=`tobytes "$OPTARG"` ;;
    o)      output=$OPTARG ;;
    v)      version ;;
    \?)     usage 1 1>&2 ;;
    esac
done
shift `expr $OPTIND - 1`

if [ -z "$bytes" ]; then
    usage 1 1>&2
fi

if [ -n "$output" -a "$output" != - ]; then
    { exec >"$output"; } 2>/dev/null
    [ $? -eq 0 ] || error "$output: cannot open"
fi

cat ${@+"$@"} | {
    IFS=

    buf=
    [ $bytes -gt 1 ] && read -n `expr $bytes - 1` buf

    c=
    while read -n 1 -r c; do
        buf="$buf$c"
        echo "$buf"
        buf="${buf#?}"
    done
}
