#!/bin/sh
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
# @(#) Command line tool for "head -c N && shift 1 byte" loop. Version 1.0.0.20151113

set -u
umask 0022
IFS=`printf ' \t\n_'`; IFS=${IFS%_}
PATH=/bin:/usr/bin
export IFS LC_ALL=C LANG=C PATH

readonly progname=`basename "$0"`

# usage <status>
usage() {
    cat <<- EOT
		usage: $progname [options] [file...]
		    -n N
		      print the N bytes per line (N >= 1)
		    -o FILE
		      place output in file FILE
	EOT
    exit $1
}

# version (nop)
version() {
    echo "$progname 1.0.0"
    exit 0
}

# error <message>
error() {
    echo "$progname:" "$@" 1>&2
    exit 1
}

# tobytes <bytes>
tobytes() {
    [ "$1" -eq 0 ] 2>/dev/null
    [ $? -lt 2 ] || return 1
    [ "$1" -ge 1 ] || return 1
    echo "$1"
}

bytes=8
output=

opt=
while getopts 'hn:o:v' opt; do
    case $opt in
    h)      usage 0 ;;
    n)      bytes=`tobytes "$OPTARG"` ;;
    o)      output=$OPTARG ;;
    v)      version ;;
    \?)     usage 1 1>&2 ;;
    esac
done
shift `expr $OPTIND - 1`

if [ -z "$bytes" ]; then
    usage 1 1>&2
fi

if [ -n "$output" -a "$output" != - ]; then
    { exec >"$output"; } 2>/dev/null
    [ $? -eq 0 ] || error "$output: cannot open"
fi

exec od -A n -t d1 -v ${@+"$@"} |
sed 's/^[ \t]*//'               |
sed 's/[ \t][ \t]*/\n/g'        |
awk '
BEGIN {
  tail = 0
}
tail < '`expr "$bytes" - 1`' {
  buf[tail++] = $0
  next
}
{
  buf[tail] = $0
  for (i = 0; i <= tail; i++)
    printf("%c", buf[i] + 0)
  printf("\n")
  for (i = 1; i <= tail; i++)
    buf[i - 1] = buf[i]
}'
